apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::445780167624:role/eksctl-eksworkshop-cluster-FargatePodExecutionRole-1QFZ6L0MMFWUH
      username: system:node:{{SessionName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::445780167624:role/eksctl-eksworkshop-cluster-nodegr-NodeInstanceRole-1F9YOSWUWMZ68
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-10-20T18:37:53Z"
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups: 
      - system:masters
      userarn: arn:aws:iam::445780167624:user/k8-study
      username: k8-study